# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
strategy:
  matrix:
    linux: 
      operatingSystems: 'ubuntu-latest'
    mac:
      operatingSystems: 'macos-latest'
pool:
  vmImage: $(operatingSystems)

steps:
- script: echo Running on $(operatingSystems)
  displayName: 'Run a one-line script'


